name: Metro
version: '1.1.0'
main: org.cubexmc.metro.Metro
api-version: '1.21'
folia-supported: true
authors: [angushushu, wwwer]
description: 一个简单的地铁管理系统
website: https://cubexmc.org

commands:
  m:
    description: Metro插件管理员命令
    aliases: [metro]
    permission: metro.admin
    usage: "§c用法: /m <line|stop|reload> [参数...]"

permissions:
  metro.admin:
    description: 允许使用Metro插件的管理员命令
    default: op
  metro.use:
    description: 允许玩家使用Metro插件功能（如乘坐地铁）
    default: true
  metro.line.create:
    description: 允许玩家创建新的地铁线路
    default: false
  metro.stop.create:
    description: 允许玩家创建新的停靠区
    default: false
