# Metro配置文件

# Title 显示配置
titles:
  # 停靠区显示（包含进入时和持续显示）
  stop_continuous:
    enabled: true
    interval: 40 # 刷新间隔，单位tick
    always: true # 是否在站台区域始终显示信息，true为持续显示，false为仅在进入时显示一次
    # 普通站点
    title: "&b{stop_name}"
    subtitle: "开往 &d{terminus_name} &f方向 | 下一站: &e{next_stop_name}"
    subtitle_with_transfers: "开往 &d{terminus_name} &f方向 | 下一站: &e{next_stop_name} | 可换乘: &a{transfer_lines}"
    actionbar: "请右击铁轨，自动搭乘 {line_color_code}{line} &f列车"
    # 始发站特殊显示
    start_stop:
      title: "&b{stop_name}"
      subtitle: "开往 &d{terminus_name} &f方向 | 始发站"
      subtitle_with_transfers: "开往 &d{terminus_name} &f方向 | 始发站 | 可换乘: &a{transfer_lines}"
      actionbar: "请右击铁轨，自动搭乘 {line_color_code}{line} &f列车"
    # 终点站特殊显示
    end_stop:
      title: "&b{stop_name}"
      subtitle: "开往 &d{stop_name} &f方向 | &e终点站"
      subtitle_with_transfers: "开往 &d{stop_name} &f方向 | &e终点站 | 可换乘: &a{transfer_lines}"
      actionbar: "本站为终点站，请进对侧站台乘车"
    # 以下选项仅在 always=false 时生效
    fade_in: 10
    stay: 40
    fade_out: 10
  
  # 到达站台时显示的title
  arrive_stop:
    enabled: true
    title: "&b{stop_name} &f到了"
    subtitle: "开往 &d{terminus_name} &f方向 | 下一站: &e{next_stop_name}"
    subtitle_with_transfers: "开往 &d{terminus_name} &f方向 | 下一站: &e{next_stop_name} | 可换乘: &a{transfer_lines}"
    fade_in: 10
    stay: 40
    fade_out: 10
    
  # 终点站显示
  terminal_stop:
    enabled: true
    title: "&b{stop_name}"
    subtitle: "&c终点站 - 请下车"
    subtitle_with_transfers: "&c终点站 - 请下车 | 可换乘: &a{transfer_lines}"
    fade_in: 10
    stay: 60
    fade_out: 10
    
  # 乘客上车后行程信息
  passenger_journey:
    enabled: true
    interval: 40 # 刷新间隔，单位tick
    title: "下一站 &e{next_stop_name}"
    subtitle: "开往 &d{terminus_name} &f方向"
    subtitle_with_transfers: "开往 &d{terminus_name} &f方向 | 可换乘: &a{transfer_lines}"
    actionbar: "列车已启动，请扶好站稳，注意安全"
    fade_in: 5
    stay: 40
    fade_out: 5

# 音乐配置
sounds:
  # 上车发车时播放的音乐
  departure:
    enabled: true
    # 音符序列，格式为 "音符,音高,音量,音色"
    # 音符可以是 NOTE (音符盒音符) 或 CUSTOM (自定义声音)
    # 音高范围：0-24 (对应F#3到F#5)
    # 音量范围：0.0-1.0
    # 对于NOTE，音色可以是：PIANO, BASS, SNARE, CLICKS, BASS_DRUM, BELL, FLUTE, CHIME, GUITAR, XYLOPHONE, IRON_XYLOPHONE, COW_BELL, DIDGERIDOO, BIT, BANJO, PLING
    notes:
      - "NOTE,12,1.0,BELL,5" # 延迟5ticks
      - "NOTE,14,1.0,BELL,5"
      - "NOTE,16,1.0,BELL,5"
      - "NOTE,19,1.0,BELL,5"
  
  # 到站时播放的音乐
  arrival:
    enabled: true
    notes:
      - "NOTE,19,1.0,BELL,5"
      - "NOTE,16,1.0,BELL,5"
      - "NOTE,14,1.0,BELL,5"
      - "NOTE,12,1.0,BELL,5"
      
  # 车辆到站时播放的音乐（列车进站时）
  station_arrival:
    enabled: true
    notes:
      - "NOTE,16,1.0,BELL,5"
      - "NOTE,19,1.0,BELL,5"
      - "NOTE,19,1.0,BELL,5"

# 计分板配置
scoreboard:
  # 站点显示样式
  styles:
    # 当前站点样式
    current_stop: "§f● "
    # 下一站样式
    next_stop: "§a● "
    # 其他站点样式
    other_stops: "§7● "
  # 线路标识符配置
  line_symbol: "■" # 所有线路统一使用的标识符，将根据线路颜色自动着色
  # 乘客计分板
  passenger:
    enabled: true
    title: "{line_color_code}{line}"
    lines:
      - "§f开往: §e{terminus_name}方向"
      - "§f终点站: §e{destination_stop_name}"
      - ""
      - "§f当前站点:"
      - "{stop_list}"

# 一般设置
settings:
  # 默认语言设置 (支持: zh_CN - 中文, en_US - 英文)
  default_language: "zh_CN"
  # 矿车移动速度
  cart_speed: 0.3
  # 矿车生成延迟（右键铁轨后多久生成矿车，单位tick，20tick=1秒）
  cart_spawn_delay: 20
  # 矿车消失延迟（下车后多久矿车消失，单位tick，20tick=1秒）
  cart_despawn_delay: 60
  # 注意：停靠区范围现在由每个停靠区的两个对角坐标点确定，此设置不再使用
  # stop_range: 5.0 