name: Metro
version: '1.0.0'
main: org.cubexmc.metro.Metro
api-version: '1.21'
authors: [angushushu, elly]
description: 一个功能简约但完善的Minecraft地铁系统插件
website: https://cubexmc.org

commands:
  m:
    description: Metro插件管理员命令
    aliases: [metro]
    permission: metro.admin
    usage: "§c用法: /m <line|stop|reload> [参数...]"

permissions:
  metro.admin:
    description: 允许使用Metro插件的管理员命令
    default: op
  metro.use:
    description: 允许玩家使用Metro插件功能（如乘坐地铁）
    default: true
